video-membership-master/courses/urls.py
from django.urls import path

from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>',
         LessonDetailView.as_view(), name='lesson-detail')
]

video-membership-master/memberships/urls.py
from django.urls import path

from .views import (
    MembershipSelectView,
    PaymentView,
    updateTransactionRecords,
    profile_view,
    cancelSubscription,
    billing_address
)

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/',
         updateTransactionRecords, name='update-transactions'),
    path('profile/', profile_view, name='profile'),
    path('cancel/', cancelSubscription, name='cancel')
]

video-membership-master/videoservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from courses.views import logout_view
from memberships.views import billing_address

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memberships/', include('memberships.urls', namespace='memberships')),
    path('', include('courses.urls', namespace='courses')),
    path('accounts/', include('allauth.urls')),
    path('billing-address/', billing_address, name='billing'),
    path('logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

video-membership-master/courses/models.py
from django.db import models
from django.urls import reverse

from memberships.models import Membership


class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    allowed_memberships = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')


class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.CharField(max_length=200)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail',
                       kwargs={
                           'course_slug': self.course.slug,
                           'lesson_slug': self.slug
                       })

video-membership-master/memberships/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from datetime import datetime
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY


MEMBERSHIP_CHOICES = (
    ('Enterprise', 'ent'),
    ('Professional', 'pro'),
    ('Free', 'free')
)


class Membership(models.Model):
    slug = models.SlugField()
    membership_type = models.CharField(
        choices=MEMBERSHIP_CHOICES,
        default='Free',
        max_length=30)
    price = models.IntegerField(default=15)
    stripe_plan_id = models.CharField(max_length=40)

    def __str__(self):
        return self.membership_type

class Address(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    address1 = models.CharField(max_length=120, blank=True)
    address2 = models.CharField(max_length=120, blank=True)
    city = models.CharField(max_length=30, blank=True)
    state = models.CharField(max_length=30, blank=True)
    zip_code = models.CharField(max_length=6, blank=True)
    country = models.CharField(max_length=120, blank=True)

    def __str__(self):
        return str(self.user)





class UserMembership(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=40)
    membership = models.ForeignKey(
        Membership, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.user.username


def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
    user_membership, created = UserMembership.objects.get_or_create(
        user=instance)


    if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
        new_customer_id = stripe.Customer.create(email=instance.email)
        try:
            free_membership = Membership.objects.get(membership_type='Free')
            user_membership.stripe_customer_id = new_customer_id['id']
            user_membership.membership = free_membership
            user_membership.save()
        except Membership.DoesNotExist:
            pass


post_save.connect(post_save_usermembership_create,
                  sender=settings.AUTH_USER_MODEL)


class Subscription(models.Model):
    user_membership = models.ForeignKey(
        UserMembership, on_delete=models.CASCADE)
    stripe_subscription_id = models.CharField(max_length=40)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.user_membership.user.username

    @property
    def get_created_date(self):
        subscription = stripe.Subscription.retrieve(
            self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.created)

    @property
    def get_next_billing_date(self):
        subscription = stripe.Subscription.retrieve(
            self.stripe_subscription_id)
        return datetime.fromtimestamp(subscription.current_period_end)

video-membership-master/memberships/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.urls import reverse

from .models import Membership, UserMembership, Subscription, Address

import stripe

import razorpay

# User = settings.AUTH_USER_MODEL

def get_user_membership(request):
    user_membership_qs = UserMembership.objects.filter(user=request.user)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None


def get_user_subscription(request):
    user_subscription_qs = Subscription.objects.filter(
        user_membership=get_user_membership(request))
    if user_subscription_qs.exists():
        user_subscription = user_subscription_qs.first()
        return user_subscription
    return None


def get_selected_membership(request):
    membership_type = request.session['selected_membership_type']
    selected_membership_qs = Membership.objects.filter(
        membership_type=membership_type)
    if selected_membership_qs.exists():
        return selected_membership_qs.first()
    return None

def get_billing_address(request):
    address_qs = Address.objects.filter(user=request.user)
    if address_qs.count() == 1:
        return address_qs.first()
    return None

@login_required
def billing_address(request):
    if request.method == "POST":
        name = request.POST["name"]
        address1 = request.POST["address1"]
        address2 = request.POST["address2"]
        city = request.POST["city"]
        state = request.POST["state"]
        zip_code = request.POST["zip_code"]
        country = request.POST["country"]

        address_obj = Address.objects.create(
                user = request.user,
                address1 = address1,
                address2 = address2,
                city = city,
                state = state,
                zip_code = zip_code,
                country = country
            )
        user_obj = User.objects.filter(username=request.user).update(first_name=name)
        messages.info(request, "Address added successfully!!!")
        return redirect("memberships:profile")

    context = {}
    return render(request, "memberships/billing_address.html", context)

@login_required
def profile_view(request):
    user_membership = get_user_membership(request)
    user_subscription = get_user_subscription(request)
    billing_obj = get_billing_address(request)
    # if billing_obj is None:
    #     return redirect('billing')
    context = {
        'user_membership': user_membership,
        'user_subscription': user_subscription,
        'address_obj': billing_obj
    }
    return render(request, "memberships/profile.html", context)


class MembershipSelectView(LoginRequiredMixin, ListView):
    model = Membership

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = get_user_membership(self.request)
        context['current_membership'] = str(current_membership.membership)
        return context

    def post(self, request, **kwargs):
        user_membership = get_user_membership(request)
        user_subscription = get_user_subscription(request)
        selected_membership_type = request.POST.get('membership_type')

        selected_membership = Membership.objects.get(
            membership_type=selected_membership_type)

        if user_membership.membership == selected_membership:
            if user_subscription is not None:
                messages.info(request, """You already have this membership. Your
                              next payment is due {}""".format('get this value from stripe'))
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        # assign to the session
        request.session['selected_membership_type'] = selected_membership.membership_type

        return HttpResponseRedirect(reverse('memberships:payment'))

@login_required
def PaymentView(request):
    billing_obj = get_billing_address(request)
    if billing_obj is None:
        return redirect('billing')

    user_membership = get_user_membership(request)
    try:
        selected_membership = get_selected_membership(request)
    except:
        return redirect(reverse("memberships:select"))
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == "POST":
        try:
            token = request.POST['stripeToken']

            # UPDATE FOR STRIPE API CHANGE 2018-05-21

            '''
            First we need to add the source for the customer
            '''

            address_qs = Address.objects.filter(user=request.user)
            address_obj = None
            if address_qs.count() == 1:
                address_obj = address_qs.first()
            if address_obj is None:
                messages.info(request, "Address is required!!")
                return redirect('memberships:profile')
            address = {
                'line1': address_obj.address1,
                'line2': address_obj.address2,
                'postal_code': address_obj.zip_code,
                'city': address_obj.city,
                'state': address_obj.state,
                'country': address_obj.country,
            }
            customer = stripe.Customer.retrieve(user_membership.stripe_customer_id)
            customer.address = address
            customer.name = request.user
            customer.source = token # 4242424242424242
            customer.save()

            # '''
            # Now we can create the subscription using only the customer as we don't need to pass their
            # credit card source anymore
            # '''

            subscription = stripe.Subscription.create(
                customer=user_membership.stripe_customer_id,
                items=[
                    # { "plan": selected_membership.stripe_plan_id },
                    {"price": selected_membership.stripe_plan_id},
                ]
            )
            return redirect(reverse('memberships:update-transactions',
                                    kwargs={
                                        'subscription_id': subscription.id
                                    }))
                

        except:
            messages.info(request, "An error has occurred, investigate it in the console")

    context = {
        'publishKey': publishKey,
        'selected_membership': selected_membership
    }

    return render(request, "memberships/membership_payment.html", context)

@login_required
def updateTransactionRecords(request, subscription_id):
    user_membership = get_user_membership(request)
    selected_membership = get_selected_membership(request)
    user_membership.membership = selected_membership
    user_membership.save()

    sub, created = Subscription.objects.get_or_create(
        user_membership=user_membership)
    sub.stripe_subscription_id = subscription_id
    sub.active = True
    sub.save()

    try:
        del request.session['selected_membership_type']
    except:
        pass

    messages.info(request, 'Successfully created {} membership'.format(
        selected_membership))
    return redirect(reverse('memberships:select'))

@login_required
def cancelSubscription(request):
    user_sub = get_user_subscription(request)

    if user_sub.active is False:
        messages.info(request, "You dont have an active membership")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
    sub.delete()

    user_sub.active = False
    user_sub.save()

    free_membership = Membership.objects.get(membership_type='Free')
    user_membership = get_user_membership(request)
    user_membership.membership = free_membership
    user_membership.save()

    messages.info(
        request, "Successfully cancelled membership. We have sent an email")
    # sending an email here

    return redirect(reverse('memberships:select'))

video-membership-master/memberships/templates/memberships/billing_address.html
{% extends 'courses/base.html' %}


{% block content %}
<div class="container">
	
	<div class="row">
		<div class="col-md-6 offset-md-4">
			<form action="{% url 'billing' %}" method="POST">
				{% csrf_token %} t
				<div class="card mt-3 mb-3 pxy-3" style="width: 18rem;">
				  <div class="card-header">
				    Billing Address
				  </div>
				  <div class="card-body">
				  	<div class="mb-3">
					  <input type="text" class="form-control" name="name" placeholder="Name" required>

					</div>
				  	<div class="mb-3">
					  <input type="text" class="form-control" name="address1" placeholder="Address 1" required>

					</div>
					<div class="mb-3">
					  <input type="text" class="form-control" name="address2" placeholder="Address 2" >

					</div>
					<div class="mb-3"> required
					  <input type="text" class="form-control" name="city" placeholder="City" required>

					</div>
					<div class="mb-3">
					  <input type="text" class="form-control" name="state" placeholder="State" required>

					</div>
					<div class="mb-3">
					  <input type="text" class="form-control" name="zip_code" placeholder="zip_code" required>

					</div>
					<div class="mb-3">
					  <input type="text" class="form-control" name="country" placeholder="country" required>

					</div>
					<div class="mb-3">
					    <button class="btn btn-primary" type="submit">Submit</button>
					  </div>
				  </div>
				  
				</div>
			</form>
		</div>
	</div>
</div>	
{% endblock content %}

video-membership-master/memberships/templates/memberships/learning.html
{% extends 'courses/base.html' %}


{% block content %}
<div class="container">
	<h4>My Profile</h4>
	<div class="row">
		<div class="card mt-3 mb-3 pxy-3" style="width: 18rem;">
		  <div class="card-header">
		    Subscription
		  </div>
		  {% if user_subscription != None %}
		  <ul class="list-group list-group-flush">
		    <li class="list-group-item">
		    	<h6>Active: {{ user_membership.membership.membership_type }} </h6>
		    	<small>since {{ user_subscription.get_created_date }}</small>
		    </li>
		    <li class="list-group-item">
		    	{% if user_subscription.active != False %}
					<p>Next payment due: {{ user_subscription.get_next_billing_date }}</p>
					<a href="{% url 'memberships:cancel' %}">Cancel subscription</a>

				{% else %}
					<p>You don't have an active membership plan. Check them out here 
						<a href="{% url 'memberships:select' %}"></a>
					</p>
				{% endif %}
		    </li>
		  </ul>
		  {% endif %}
		</div>
		<div class="card mt-3 mb-3 pxy-3" style="width: 18rem;">
		  <div class="card-header">
		    Billing Address
		  </div>
		  {% if address_obj %}
		  <ul class="list-group list-group-flush">
		    <li class="list-group-item">
		    	Address1: {{address_obj.address1}} 
		    </li>
		    {% if address_obj.address2 %}
		    <li class="list-group-item">
		    	Address2: {{address_obj.address2}} 
		    </li>
		    {% endif %}
		     <li class="list-group-item">
		    	City: {{address_obj.city}} 
		    </li>
		    <li class="list-group-item">
		    	State: {{address_obj.state}} 
		    </li>
		    <li class="list-group-item">
		    	Zip_code: {{address_obj.zip_code}} 
		    </li>
		    <li class="list-group-item">
		    	Country: {{address_obj.country}} 
		    </li>
		  </ul>
		  {% endif %}
		</div>
	</div>
</div>	
{% endblock content %}

video-membership-master/memberships/templates/memberships/membership_list.html
{% extends 'courses/base.html' %}


{% block content %}
<div class="container">
	<h2>Select a membership</h2>
	<div class="row">
		{% for object in object_list %}
		<div class="col-sm-4 col-md-4 border border-primary mt-3 mb-5">
			<h2>{{ object.membership_type }}</h2>
			<p>Price: ${{ object.price }}<small>/month</small></p>
			<h4>Included Courses</h4>
			<ul>
				{% for course in object.course_set.all %}
					<li>{{ course.title }}</li>
				{% endfor %}
			</ul>
			{% if object.membership_type != 'Free' %}
			<form method="POST" action="{% url 'memberships:select' %}">
				{% csrf_token %}
				{% if object.membership_type != current_membership %}
					<button class="btn btn-warning">Select</button>
				{% else %}
					<small>This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>			
			{% endif %}	
		</div>
		{% endfor %}
	</div>
</div>



{% endblock content %}

video-membership-master/memberships/templates/memberships/profile.html
{% extends 'courses/base.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<h1>My Profile</h1>
		<div class="col-sm-4 col-md-4">
			<!-- {% if user_subscription != None %}
				<h4>Current Membership: {{ user_membership.membership.membership_type }} <small>since {{ user_subscription.get_created_date }}</small></h4>

				{% if user_subscription.active != False %}
					<p>Next payment due: {{ user_subscription.get_next_billing_date }}</p>
					<a href="{% url 'memberships:cancel' %}">Cancel subscription</a>

				{% else %}
					<p>You don't have an active membership plan. Check them out here 
						<a href="{% url 'memberships:select' %}"></a>
					</p>
				{% endif %}
			{% endif %} -->
		</div>
	</div>
</div>	
{% endblock content %}