video-membership-master/courses/urls.py
from django.urls import path

from .views import CourseListView, CourseDetailView, LessonDetailView

app_name = 'courses'

urlpatterns = [
    path('', CourseListView.as_view(), name='list'),
    path('<slug>', CourseDetailView.as_view(), name='detail'),
    path('<course_slug>/<lesson_slug>',
         LessonDetailView.as_view(), name='lesson-detail')
]

video-membership-master/memberships/urls.py
from django.urls import path

from .views import (
    MembershipSelectView,
    PaymentView,
    updateTransactionRecords,
    profile_view,
    cancelSubscription,
    billing_address
)

app_name = 'memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select'),
    path('payment/', PaymentView, name='payment'),
    path('update-transactions/<subscription_id>/',
         updateTransactionRecords, name='update-transactions'),
    path('profile/', profile_view, name='profile'),
    path('cancel/', cancelSubscription, name='cancel')
]

video-membership-master/videoservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from courses.views import logout_view
from memberships.views import billing_address

urlpatterns = [
    path('admin/', admin.site.urls),
    path('memberships/', include('memberships.urls', namespace='memberships')),
    path('', include('courses.urls', namespace='courses')),
    path('accounts/', include('allauth.urls')),
    path('billing-address/', billing_address, name='billing'),
    path('logout/', logout_view, name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

video-membership-master/courses/models.py
from django.db import models
from django.urls import reverse

from memberships.models import Membership


class Course(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    description = models.TextField()
    allowed_memberships = models.ManyToManyField(Membership)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:detail', kwargs={'slug': self.slug})

    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')


class Lesson(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=120)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    position = models.IntegerField()
    video_url = models.CharField(max_length=200)
    thumbnail = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('courses:lesson-detail',
                       kwargs={
                           'course_slug': self.course.slug,
                           'lesson_slug': self.slug
                       })

video-membership-master/courses/forms.py
from allauth.account.forms import LoginForm, SignupForm

##ref https://gavinwiener.medium.com/modifying-django-allauth-forms-6eb19e77ef56

class MyCustomLoginForm(LoginForm):

    def __init__(self, *args, **kwargs):
        super(MyCustomLoginForm, self).__init__(*args, **kwargs)
        # for fieldname, field in self.fields.items():
        #     field.widget.attrs.update({
        #         'class': 'form-control'
        #     })
        self.fields['login'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['password'].widget.attrs.update({
            'class': 'form-control'
        })

    # def login(self, *args, **kwargs):

    #     # Add your own processing here.

    #     # You must return the original result.
    #     return super(MyCustomLoginForm, self).login(*args, **kwargs) 



class MyCustomSignupForm(SignupForm):
    
    def __init__(self, *args, **kwargs):
        super(MyCustomSignupForm, self).__init__(*args, **kwargs)
        for fieldname, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control'
            })
    
    # def save(self, request):
    #     organization = self.cleaned_data.pop('organization')
    #     ...
    #     user = super(MyCustomSignupForm, self).save(request)

video-membership-master/courses/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.views.generic import ListView, DetailView, View
from memberships.models import UserMembership
from .models import Course, Lesson

def logout_view(request):
    logout(request) 
    return redirect('courses:list')




class CourseListView(ListView):
    model = Course


class CourseDetailView(DetailView):
    model = Course


class LessonDetailView(LoginRequiredMixin, View):

    def get(self, request, course_slug, lesson_slug, *args, **kwargs):
        course = get_object_or_404(Course, slug=course_slug)
        lesson = get_object_or_404(Lesson, slug=lesson_slug)
        user_membership = get_object_or_404(UserMembership, user=request.user)
        user_membership_type = user_membership.membership.membership_type
        course_allowed_mem_types = course.allowed_memberships.all()
        context = { 'object': None }
        if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
            context = {'object': lesson}
        return render(request, "courses/lesson_detail.html", context)

video-membership-master/courses/templates/courses/base.html
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<title>Django Video Membership</title>
</head>
<body>

	
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <div class="container">
		    <a class="navbar-brand" href="#">DVideoMem</a>
		    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		      <span class="navbar-toggler-icon"></span>
		    </button>
		    <div class="collapse navbar-collapse" id="navbarSupportedContent">
		      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
		        <li class="nav-item">
		          <a class="nav-link active" aria-current="page" href="/">Courses</a>
		        {% if request.user.is_authenticated %}
		        <li class="nav-item">
		          <a class="nav-link" href="/memberships/">Membership</a>
		        </li>
		        <li class="nav-item dropdown">
		          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
		            {{request.user|title}}
		          </a>
		          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
		            <li><a class="dropdown-item" href="{% url 'memberships:profile' %}">Profile</a></li>
		            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
		          </ul>
		        </li>
		        {% else %}
		        <li class="nav-item">
		          <a class="nav-link" href="/accounts/login">Login</a>
		        </li>
		        {% endif %}
		      </ul>
		      <form class="d-flex">
		        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
		        <button class="btn btn-outline-success" type="submit">Search</button>
		      </form>

		    </div>
		  </div>
		</nav>

	

			{% include 'courses/messages.html' %}

			{% block content %}
			{% endblock content %}


	<script
  	src="https://code.jquery.com/jquery-3.3.1.js"
  	integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  	crossorigin="anonymous"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	 <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script type="text/javascript">
      // Alert message 
      $(document).ready(function(){
          $(".close").click(function(){
            $("#myAlert").alert("close");
          });
      });

      setTimeout(function(){
          $('#message').fadeOut('slow');
      }, 3000);

      //end alert message
    </script>
</body>
</html>

video-membership-master/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
<li>{{ object.title }}</li>
{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Course Detail</h3> 
				<hr />
				<h4>{{ object.title | title }}</h4>
				<hr />
				<p>{{ object.description|title }}</p>
				<ol>
					{% for lesson in object.lessons %}
					<li><a href="{{ lesson.get_absolute_url }}">{{ lesson.title|title }}</a></li>
					{% endfor %}
				</ol>
				
			</div>
		</div>
	</div>

{% endblock %}

video-membership-master/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}

{% block content %}
	<div class="container">
		<div class="row mt-5">
			<div class="card" style="">
			  <div class="card-header">
			    Course List
			  </div>
			  <ul class="list-group list-group-flush">
			  	{% for object in object_list %}
			    	<li class="list-group-item"><p><a href="{{ object.get_absolute_url }}">{{ object }}</a></p></li>
			    {% endfor %}
			  </ul>
			</div>
		</div>
	</div>
{% endblock %}

video-membership-master/courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
{% if object is not None %}
	<li><a href="{{ object.course.get_absolute_url }}">{{ object.course.title }}</a></li>
	<li>{{ object.title }}</li>
{% endif %}
{% endblock %}

{% block content %}
	<div class='container'>
		<h1>Lesson Detail View</h1>
		<div class='row'>
			<div class='col-sm-6 col-md-6'>
				{% if object is not None %}
				<h3>{{ object.title }}</h3>
				<p>{{ object.description }}</p>
				
				<video controls
					   controlsList="nodownload"
					   poster="{{ object.thumbnail.url }}"
				       src="/static{{ object.video_url }}"
				       width="300"
				       height="200">
				    Sorry, your browser doesn't support embedded videos.
				</video>
				{% else %}
				<h3>Upgrade membership</h3>
				<p>To view this course you'll need to upgrade your membership</p>
				<br>
				<a href="{% url 'memberships:select' %}"><button class="btn btn-warning">Check out memberships</button></a>
				<hr>
				{% endif %}
			</div>
		</div>
	</div>

{% endblock content %}

video-membership-master/courses/templates/courses/messages.html
{% if messages %}

   {% for message in messages %} 
        <div class="container" id="message">
                <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>

                    </button>
                    <strong>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                           Error:
                        {% else %} 
                           {{ message.tags|title}}
                        {% endif %}
                    </strong>
                    {{ message }}
                </div>
        </div>
   {% endfor %}

{% endif %}